//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnquiryGroup
    {
        public EnquiryGroup()
        {
            this.EnquiryCategories = new HashSet<EnquiryCategory>();
        }
    
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public Nullable<double> SerialNumber { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> InActiveDate { get; set; }
        public Nullable<int> InActiveBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual ICollection<EnquiryCategory> EnquiryCategories { get; set; }
    }
}
