//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialUnit
    {
        public MaterialUnit()
        {
            this.MaterialMasters = new HashSet<MaterialMaster>();
        }
    
        public int Id { get; set; }
        public string UnitName { get; set; }
        public string UnitDecsription { get; set; }
        public Nullable<double> SerialNumber { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> InActiveDate { get; set; }
        public Nullable<int> InActineBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual ICollection<MaterialMaster> MaterialMasters { get; set; }
    }
}
