//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hasten_AMSEntities : DbContext
    {
        public hasten_AMSEntities()
            : base("name=hasten_AMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EnquiryCategory> EnquiryCategories { get; set; }
        public DbSet<EnquiryGroup> EnquiryGroups { get; set; }
        public DbSet<EnquiryStatu> EnquiryStatus { get; set; }
        public DbSet<EnquiryType> EnquiryTypes { get; set; }
        public DbSet<FollowUp> FollowUps { get; set; }
        public DbSet<Inquiry> Inquiries { get; set; }
        public DbSet<Inspection> Inspections { get; set; }
        public DbSet<InspectionMaterial> InspectionMaterials { get; set; }
        public DbSet<MaterialMaster> MaterialMasters { get; set; }
        public DbSet<MaterialUnit> MaterialUnits { get; set; }
        public DbSet<ProfileSentDetail> ProfileSentDetails { get; set; }
        public DbSet<UserMaster> UserMasters { get; set; }
        public DbSet<UserRoleType> UserRoleTypes { get; set; }
    }
}
